# Generated by Django 5.2.1 on 2025-05-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='date',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
